steps:

# Step 0: Install Node modules
- id: 'Install Node Modules'
  name: node:lts
  args: ['yarn', 'install', '--frozen-lockfile']

# Step 1: Run Javascript tests with Mocha.js
- id: 'Run Javascript tests with Mocha.js'
  name: node:lts
  args: ['yarn', 'test']

# Step 2: Install Composer managed dependencies
- id: 'Install Composer vendor packages'
  name: composer
  args: ['composer', 'install', '--ignore-platform-reqs', '--working-dir=./src'] # for WP we'd use '--working-dir=./app' as well

# Step 3: Run PHP tests with PHPUnit and Mockery tests
- id: 'Run PHP tests with PHPUnit and Mockery tests'
  name: skwid138/php7-phpunit-mockery:latest
  args: ['phpunit', '--bootstrap', 'src/vendor/autoload.php', 'tests']
