steps:

  # Step 0: Install Node modules
  - id: 'Install frontend packages'
    name: node:12-alpine
    entrypoint: yarn
    args: ['install', '--frozen-lockfile']

  # Step 1: Run Javascript tests with Mocha.js
  - id: 'Run Javascript tests with Mocha.js'
    name: node:12-alpine
    entrypoint: yarn
    args: ['test']

  # Step 3: Bundle and minify JS, and Scss
#  - id: 'Build frontend packages'
#    name: node:12-alpine
#    entrypoint: yarn
#    args: ['build:prod']

  # Step 2: Install Composer managed dependencies
  - id: 'Install backend packages'
    name: composer
    entrypoint: composer
    args: [ 'install', '--ignore-platform-reqs', '--working-dir=./src'] # for WP we'd use '--working-dir=./app' as well

  # Step 3: Run PHP tests with PHPUnit and Mockery tests
  - id: 'Run PHP tests with PHPUnit and Mockery tests'
    name: skwid138/php7-phpunit-mockery:latest
    entrypoint: phpunit
    args: [ '--bootstrap', 'src/vendor/autoload.php', 'tests' ]
